### ISSUE TITLE
Error in skvideo.io.vread

### ISSUE THREAD

**Issue by Rishi2309** [kmr0877/Vehicle-and-Speed-Identification#2]
Warning (from warnings module):
  File "C:\Users\Rishi\AppData\Local\Programs\Python\Python37\lib\site-packages\skvideo\__init__.py", line 306
    warnings.warn("ffmpeg/ffprobe not found in path: " + str(path), UserWarning)
UserWarning: ffmpeg/ffprobe not found in path: /usr/local/lib/site-packages/ffmpeg
Traceback (most recent call last):
  File "C:\Users\Rishi\Desktop\Vehicle-and-Speed-Identification-master\speed_detect.py", line 30, in <module>
    cap = skvideo.io.vread('1.mp4')
  File "C:\Users\Rishi\AppData\Local\Programs\Python\Python37\lib\site-packages\skvideo\io\io.py", line 133, in vread
    assert _HAS_FFMPEG, "Cannot find installation of real FFmpeg (which comes with ffprobe)."
AssertionError: Cannot find installation of real FFmpeg (which comes with ffprobe).

**Comment by Sivabanu** [comment]
Same error here
